---
- name: Install dependencies
  ansible.builtin.apt:
    name:
      - dmsetup
      - cryptsetup
      - nfs-common
      - open-iscsi

- name: Ensure iscsid loaded
  community.general.modprobe:
    name: iscsi_tcp
    rpi_state: present
    persistent: present
