---
- name: Execute OS related tasks on the Raspberry Pi - teardown
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - "system/{{ detected_distribution }}-{{ detected_distribution_major_version }}.yml"
    - "system/{{ detected_distribution }}.yml"
    - "system/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "system/{{ ansible_distribution }}.yml"
    - "system/default.yml"
  when:
    - raspberry_pi|default(false)

- name: Execute packages related tasks - teardown
  ansible.builtin.include_tasks: "packages.yml"
  when:
    - install_longhorn_dependencies|default(true)
